#!/bin/bash

# Retrieve arguments
app=sonerezh
domain=$1
url_path=$2
#admin=$3
#is_public=$4

# Save app settings
#sudo yunohost app setting $app admin -v "$admin"
#sudo yunohost app setting $app is_public -v "$is_public"

# Check domain/path availability
sudo yunohost app checkurl $domain$url_path -a $app \
	|| (echo "Path not available: $domain$url_path" && exit 1)

# Initiate MySQL database
db_pwd=$(openssl rand -hex 15)
sudo yunohost app initdb $app -p $db_pwd
sudo yunohost app setting $app mysqlpwd -v $db_pwd

# Install dependency to convert tracks to a readable format for the browser
#sudo apt-get install libav-tools

# Copy sources to the web directory
src_path=/var/www/sonerezh
sudo mkdir -p $src_path
sudo cp -a ../sources/. $src_path

# Set permissions to sonerezh directory
sudo chown -R www-data: $src_path
sudo chmod -R 775 $src_path

# Configure data repository
data_path=/home/yunohost.app/sonerezh/data
sudo mkdir -p $data_path

# Modify Nginx configuration file and copy it to Nginx conf directory
sed -i "s@YNH_WWW_PATH@$url_path@g" ../conf/nginx.conf
sed -i "s@YNH_WWW_ALIAS@$src_path/app@g" ../conf/nginx.conf
sed -i "s@YNH_WWW_APP@$app@g" ../conf/nginx.conf
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/$app.conf

# Modify PHP configuration file and coyp it to PHP conf directory
php_conf=/etc/php5/fpm/pool.d/$app.conf
#sed -i "s@YNH_WWW_PATH@$url_path@g" ../conf/php-fpm.conf
sed -i "s@YNH_WWW_ALIAS@$app/app/webroot@g" ../conf/php-fpm.conf
sed -i "s@YNH_WWW_APP@$app@g" ../conf/php-fpm.conf
sudo cp ../conf/php-fpm.conf $php_conf
sudo chown root: $php_conf
sudo chmod 644 $php_conf

# If app is public, add url to SSOWat conf as skipped_uris
#if [ "$is_public" = "Yes" ];
#then
  # unprotected_uris allows SSO credentials to be passed anyway.
#    sudo yunohost app setting $app unprotected_uris -v "/"
#fi

# Reload Nginx and PHP conf
sudo service nginx reload
sudo service php5-fpm reload
