#!/bin/bash

# Retrieve arguments
app=sonerezh
domain=$1
url_path=$2
email_auth=$3
password=$4
music_path=/home/yunohost.app/sonerezh

# Save app settings
sudo yunohost app setting $app music_path -v "$music_path"

# Check password length
if [ ! ${#password} -ge 8 ]; then echo "password length must be ≥ 8 characters." && exit 1
fi

# Check url path is not root
if [[ $url_path == "/" ]]; then
echo "Currently Sonerezh can only be installed on a subpath domain" && exit 1
fi

# Check domain/path availability
sudo yunohost app checkurl $domain$url_path -a $app \
	|| (echo "Path not available: $domain$url_path" && exit 1)

# Install dependency to convert tracks to a readable format for the browser
sudo apt-get -y -qq install libav-tools

# Create music repository
sudo mkdir -p $music_path

# Install sources
src_path=/var/www/sonerezh
sudo mkdir -p $src_path
sudo cp -a ../sources/. $src_path
sudo chown -R www-data: $src_path
sudo chmod -R 775 $src_path

# Initiate MySQL database
db_pwd=$(openssl rand -hex 15)
sudo yunohost app initdb $app -p $db_pwd
sudo yunohost app setting $app mysqlpwd -v $db_pwd

# Configure Nginx
nginxconf=../conf/nginx-subpath.conf
sed -i "s@YNH_WWW_PATH@$url_path@g" $nginxconf
sed -i "s@YNH_WWW_ALIAS@$src_path/app/webroot@g" $nginxconf
sed -i "s@YNH_WWW_APP@$app@g" $nginxconf
sudo cp $nginxconf /etc/nginx/conf.d/$domain.d/$app.conf

# Configure PHP
php_conf=/etc/php5/fpm/pool.d/$app.conf
sed -i "s@YNH_WWW_ALIAS@$app/app/webroot@g" ../conf/php-fpm.conf
sed -i "s@YNH_WWW_APP@$app@g" ../conf/php-fpm.conf
sudo cp ../conf/php-fpm.conf $php_conf
sudo chown root: $php_conf
sudo chmod 644 $php_conf

# Set app public
sudo yunohost app setting $app unprotected_uris -v "/"
sudo yunohost app ssowatconf

# Reload Nginx and PHP conf
sudo service nginx reload
sudo service php5-fpm reload

# Add alias line in hosts file
echo "127.0.0.1 $domain # $app" | sudo tee -a /etc/hosts

# Postinstall on web interface
sleep 1 && curl -k \
-d "data[DB][datasource]=MySQL" \
-d "data[DB][host]=localhost" \
-d "data[DB][database]=$app" \
-d "data[DB][login]=$app" \
-d "data[DB][password]=$db_pwd" \
-d "data[DB][prefix]=$app_" \
-d "data[User][email]=$email_auth"
-d "data[User][password]=$password" \
-d "data[User][confirm_password]=$password" \
-d "[Setting][Rootpath][0][rootpath]=$music_path" \
https://$domain$url_path/install

# Remove alias line from hosts file
sudo sed -i "/# $app/d" /etc/hosts
