#!/bin/bash

# Source YunoHost helpers
source /usr/share/yunohost/helpers

# Retrieve arguments
app=$YNH_APP_INSTANCE_NAME
domain=$(ynh_app_setting_get $app domain)
url_path=$(ynh_app_setting_get $app path)
music_path=$(ynh_app_setting_get $app music_path)

# Remove sources
sudo rm -rf /var/www/$app

# Remove music
#sudo rm -rf $music_path # could replace bottom line when issue #238 will be solved
sudo rmdir $music_path

# Remove database
root_pwd=$(sudo cat /etc/yunohost/mysql)
mysql -u root -p$root_pwd -e "DROP DATABASE $app ; DROP USER $app@localhost ;"

# Remove Nginx and PHP configuration files
sudo rm -f /etc/nginx/conf.d/$domain.d/$app.conf
sudo rm -f /etc/php5/fpm/pool.d/$app.conf

# Reload services
sudo service php5-fpm reload
sudo service nginx reload
