#!/bin/bash

# Retrieve arguments
app=sonenezh
domain=$(sudo yunohost app setting $app domain)
path=$(sudo yunohost app setting $app path)
#admin=$(sudo yunohost app setting $app admin)
#is_public=$(sudo yunohost app setting $app is_public)

# Remove sources
sudo rm -rf /var/www/$app

# Remove database
root_pwd=$(sudo cat /etc/yunohost/mysql)
mysql -u root -p $root_pwd -e "DROP DATABASE $app ; DROP USER $app@localhost ;"

# Remove Nginx and PHP configuration files
sudo rm -f /etc/nginx/conf.d/$domain.d/$app.conf
sudo rm -f /etc/php5/fpm/pool.d/$app.conf

# Reload services
sudo service php5-fpm reload
sudo service nginx reload
