#!/bin/bash

# Retrieve arguments
app=sonerezh
domain=$(sudo yunohost app setting $app domain)
url_path=$(sudo yunohost app setting $app path)
#is_public=$(sudo yunohost app setting $app is_public)
music_path=$(sudo yunohost app setting $app music_path)

# Remove sources
sudo rm -rf /var/www/$app

# Remove music
#sudo rm -rf $music_path # could replace bottom line when issue #238 will be solved
sudo rmdir $music_path

# Remove database
root_pwd=$(sudo cat /etc/yunohost/mysql)
mysql -u root -p$root_pwd -e "DROP DATABASE $app ; DROP USER $app@localhost ;"

# Remove Nginx and PHP configuration files
sudo rm -f /etc/nginx/conf.d/$domain.d/$app.conf
sudo rm -f /etc/php5/fpm/pool.d/$app.conf

# Reload services
sudo service php5-fpm reload
sudo service nginx reload
