#!/bin/bash

# causes the shell to exit if any subcommand or pipeline returns a non-zero status
set -e

app=sonerezh

# The parameter $1 is the uncompressed restore directory location
backup_dir=$1/apps/$app

# Restore sources & data
src_path=/var/www/$app
sudo mkdir -p $src_path
sudo cp -a $backup_dir/sources/. $src_path

# Restore permissions to app files
sudo chown -R www-data: $src_path

# Restore MySQL database
db_pwd=$(sudo yunohost app setting $app mysqlpwd)
sudo mysql -u $app -p$db_pwd $app < $backup_dir/$app.dmp

# Restore Nginx and YunoHost parameters
sudo cp -a $backup_dir/yunohost/. /etc/yunohost/apps/$app
domain=$(sudo yunohost app setting $app domain)
sudo cp -a $backup_dir/nginx.conf /etc/nginx/conf.d/$domain.d/$app.conf

# Copy dedicated php-fpm process from backup folder to the right location
sudo cp -a $backup_dir/php-fpm.conf /etc/php5/fpm/pool.d/$app.conf
sudo service php5-fpm reload

# Reload webserver
sudo service nginx reload
