#!/bin/bash

# causes the shell to exit if any subcommand or pipeline returns a non-zero status
set -e

# Retrieve arguments
app=sonerezh
domain=$(sudo yunohost app setting $app domain)
url_path=$(sudo yunohost app setting $app path)

# Install sources
src_path=/var/www/$app
sudo mkdir -p $src_path
sudo cp -a ../sources/. $src_path
sudo chown -R www-data: $src_path
sudo chmod -R 775 $src_path

# Configure Nginx
nginxconf=../conf/nginx-subpath.conf
sed -i "s@YNH_WWW_PATH@$url_path@g" $nginxconf
sed -i "s@YNH_WWW_ALIAS@$src_path/app/webroot@g" $nginxconf
sed -i "s@YNH_WWW_APP@$app@g" $nginxconf
sudo cp $nginxconf /etc/nginx/conf.d/$domain.d/$app.conf

# Configure PHP
php_conf=/etc/php5/fpm/pool.d/$app.conf
sed -i "s@YNH_WWW_ALIAS@$app/app/webroot@g" ../conf/php-fpm.conf
sed -i "s@YNH_WWW_APP@$app@g" ../conf/php-fpm.conf
sudo cp ../conf/php-fpm.conf $php_conf
sudo chown root: $php_conf
sudo chmod 644 $php_conf

# Set app public
sudo yunohost app setting $app unprotected_uris -v "/"

# Reload services
sudo service php5-fpm reload
sudo service nginx reload
